# Generated by Django 4.2.5 on 2023-09-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
