# Generated by Django 4.2.5 on 2023-10-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_patient_next_of_kin_alter_ward_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='DOB',
            field=models.DateField(),
        ),
    ]
