# Generated by Django 4.2.5 on 2023-10-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
